# Generated by Django 5.0 on 2024-01-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
