# Generated by Django 5.0 on 2024-01-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_group_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
