# Generated by Django 5.0 on 2024-01-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(max_length=40, unique=True)),
                ('username', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('name', models.CharField(max_length=40, null=True)),
                ('language', models.CharField(choices=[('uz_lt', 'Uzbek'), ('en_kr', 'Ўзбек')], default='uz_lt', max_length=6)),
                ('step', models.SmallIntegerField(choices=[(1, 'Listing language'), (2, 'Edit language'), (3, 'Main menu')], default=1)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
